### ISSUE TITLE
Also works on Surface Pro 6 (2018)

### ISSUE THREAD

**Issue by talal** [qzed/linux-surfacegen5-acpi#10]
First of all thank you for your great work.

This is not an issue, but rather an FYI: I just wanted to let you that this also works for Surface Pro 6 (2018).

Simply doing a `sudo dpkg -i` on the latest image, header, and libc-dev `.deb` files from your fork and adding the `CONFIG_SERIAL_...` values mentioned in the README to `/etc/sysctl.conf` (hopefully this is the right place to enter them :sweat_smile: ) worked.

**Comment by qzed** [comment]
Awesome, thanks! I'll update the readme to reflect this!
