### ISSUE TITLE
make module error

### ISSUE THREAD

**Issue by doomdevelop** [qzed/linux-surfacegen5-acpi#11]
Hi ,
Thank you so much for the work on the "power status" issue for the surface devices.
My device is surface 2017.
 I get your precompiled kernel and did make . Unfortunately get error..
I am "passive" linux user , maybe I just did stupid mistake , could you please look in to this error ? 
Thank you!

yo@yo-Surface-Pro:~/git/linux-surfacegen5-acpi/module$ sudo make
make -C /lib/modules/"4.18.20-surface+"/build M= modules
make[1]: Entering directory '/usr/src/linux-headers-4.18.20-surface+'
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/include/generated/asm/syscalls_32.h'. Stop.
make[1]: *** [arch/x86/Makefile:255: archheaders] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.18.20-surface+'
make: *** [Makefile:23: all] Error 2

**Comment by doomdevelop** [comment]
I could build without the modul without sudo . 
But get the stuck during insmod> 

yo@yo-Surface-Pro:~/git/linux-surfacegen5-acpi/module$ sudo insmod surfacegen5_acpi
[sudo] password for yo: 
insmod: ERROR: could not load module surfacegen5_acpi: No such file or directory

**Comment by qzed** [comment]
Ahh I messed that up in the readme: You need to run `sudo insmod surfacegen5_acpi.ko` (with the `.ko` ending). Sorry for the inconvenience, I'll fix that immediately!

**Comment by doomdevelop** [comment]
Great ! The Power State is working !
Thank you so much !
