### ISSUE TITLE
Ubuntu not installing properly on Surface Laptop 3

### ISSUE THREAD

**Issue by Sallysegui** [qzed/linux-surfacegen5-acpi#23]
I just purchased SL3 and have tried to install Ubuntu but so far have been unsuccessful. Could someone please provide a step by step tutorial for beginners. I couldn't install Ubuntu 18.04, I manage to install 16.04 but the track pad and keyboard are not working, I've read numerous threads but I don't quite understand.

**Comment by qzed** [comment]
Sorry, but this is the wrong repo for that. You should have a look at https://github.com/jakeday/linux-surface/issues/591 and specifically https://github.com/jakeday/linux-surface/issues/592#issuecomment-546954750 (blacklist `intel_lpss_pci`). If those issues don't help you can ask around on gitter or IRC, or open a new issue on https://github.com/jakeday/linux-surface/issues.

This repo is only for the surface-acpi/EC drivers. Also, keyboard and trackpad support is already tracked in #22.
